"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
import glob

APP = ['QT_GUI.py']
DATA_FILES = ["GuiDesign.ui","Configurator.py"]

for file in glob.glob("PyCorrector/*"):
    if file not in DATA_FILES:
        DATA_FILES.append(file)

OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
